development:
  adapter: mysql2
  encoding: utf8
  database: review_system_development
  username: root
  password:
test:
  adapter: mysql2
  encoding: utf8
  database: review_system_test
  username: root
  password:

